name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cityscapes:latest
    - name: login
      run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_TOKEN}}
    - name: Tag the Docker image
      run: docker tag cityscapes:latest ${{secrets.DOCKER_HUB_USERNAME}}/Cityscapes:latest
    - name: push the Docker image
      run: docker push username/repo_name:latest
